## Getting Started

- Topics
1. How to print
2. How to assign variables
3. How to comment
4. Syntax for basic Math

### How to Print

In Julia, we use **println()** to print

In [94]:
println("I am new to Julia")    # do not use single quotation mark ( ' ')

I am new to Julia


### How to assign a variable

**typeof()** will figure out types for us

In [96]:
my_answer = 42
typeof(my_answer)

Int64

In [97]:
my_pi = 3.1416
typeof(my_pi)

Float64

In [98]:
😺 = "My name is Mujahid"  # Do not use single quote mark in julia (' ')
typeof(😺)

String

To type a smiley cat, use tab completion to select the emoji name and then tab again

In [100]:
# \:smi +  --> select with down arrow +  --->  +  to complete

In [101]:
😺 = 1
typeof(😺)

Int64

Note: Julia allows us to write super generic code, and 😺 is an example of this.

This allows us to write code like

In [103]:
😀 = 0
😞 = -1

-1

In [104]:
😺 + 😞 == 😀

true

### How to comment

In [106]:
# you can comment on a single line like this

In [107]:
#= 

For multi-line comment, 
use '#= =#' sequence

=#

### Syntax for basic Math

In [1]:
sum = 1 + 3

4

In [110]:
differences = 5 - 3

2

In [111]:
product = 20 * 5

100

In [112]:
quotient = 100 / 10

10.0

In [113]:
power = 10 ^ 2

100

In [114]:
modulus = 101 % 2

1

### Exercises

#### 1.1

Look up docs for the convert function.

The convert function is used to explicitly convert a value x to a specified type T. For example, **convert(Float64, 5)** converts the integer 5 into a floating-point number 5.0.

In [8]:
?convert

search: convert Base.cconvert collect const



```julia
convert(T, x)
```

Convert `x` to a value of type `T`.

If `T` is an [`Integer`](@ref) type, an [`InexactError`](@ref) will be raised if `x` is not representable by `T`, for example if `x` is not integer-valued, or is outside the range supported by `T`.

# Examples

```jldoctest
julia> convert(Int, 3.0)
3

julia> convert(Int, 3.5)
ERROR: InexactError: Int64(3.5)
Stacktrace:
[...]
```

If `T` is a [`AbstractFloat`](@ref) type, then it will return the closest value to `x` representable by `T`. Inf is treated as one ulp greater than `floatmax(T)` for purposes of determining nearest.

```jldoctest
julia> x = 1/3
0.3333333333333333

julia> convert(Float32, x)
0.33333334f0

julia> convert(BigFloat, x)
0.333333333333333314829616256247390992939472198486328125
```

If `T` is a collection type and `x` a collection, the result of `convert(T, x)` may alias all or part of `x`.

```jldoctest
julia> x = Int[1, 2, 3];

julia> y = convert(Vector{Int}, x);

julia> y === x
true
```

See also: [`round`](@ref), [`trunc`](@ref), [`oftype`](@ref), [`reinterpret`](@ref).


#### 1.2

Assign 365 to a variable named days. Convert days to a float and assign it to variable days_float

In [14]:
days = 365
days_float = convert(Float64, 365)

365.0

In [21]:
days

365

In [23]:
days_float

365.0

@assert days == 365

@assert days_float == 365.0

The assertions confirm that days is still 365 and days_float is now 365.0

#### 1.3

See what happens when you execute

convert(Int64, "1")
and

parse(Int64, "1")

In [16]:
convert(Int64, "1")

LoadError: MethodError: [0mCannot `convert` an object of type [92mString[39m[0m to an object of type [91mInt64[39m
The function `convert` exists, but no method is defined for this combination of argument types.

[0mClosest candidates are:
[0m  convert(::Type{T}, [91m::T[39m) where T<:Number
[0m[90m   @[39m [90mBase[39m [90m[4mnumber.jl:6[24m[39m
[0m  convert(::Type{T}, [91m::Number[39m) where T<:Number
[0m[90m   @[39m [90mBase[39m [90m[4mnumber.jl:7[24m[39m
[0m  convert(::Type{T}, [91m::T[39m) where T
[0m[90m   @[39m [90mBase[39m [90m[4mBase_compiler.jl:133[24m[39m
[0m  ...


**Convert cannot directly convert a string ("1") into an integer (Int64).** *The convert function is strict and expects the input to already be of a compatible type (e.g., converting between numeric types).*

In [18]:
parse(Int64, "1")

1

**The parse function is specifically designed to interpret strings as values of a given type.**

**Parses strings into Int64.Works only with strings**